name: 'Telemetry write mTLS files'
description: 'writes certificates to disk and sets env vars so that OpenTelemetry stuff can find them'
inputs:
  ca_cert:
    description: Text of the ca certificate for mTLS. This is NOT the file path. It is the secret value.
  client_cert:
    description: Text of the client certificate for mTLS. This is NOT the file path. It is the secret value.
  client_key:
    description: Text of the client key for mTLS. This is NOT the file path. It is the secret value.

runs:
  using: 'composite'
  steps:
    - name: Write certificate files for mTLS
      shell: bash
      run: |
        mkdir -p /tmp/certs
        OTEL_EXPORTER_OTLP_CERTIFICATE=/tmp/certs/ca.crt.pem
        cat << EOF > "${OTEL_EXPORTER_OTLP_CERTIFICATE}"
        ${{ inputs.ca_cert }}
        EOF
        echo OTEL_EXPORTER_OTLP_CERTIFICATE=${OTEL_EXPORTER_OTLP_CERTIFICATE} >> ${GITHUB_ENV}

        OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE=/tmp/certs/client.crt.pem
        cat << EOF > "${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}"
        ${{ inputs.client_cert }}
        EOF
        echo OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE=${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE} >> ${GITHUB_ENV}

        OTEL_EXPORTER_OTLP_CLIENT_KEY=/tmp/certs/client.key.pem
        cat << EOF > "${OTEL_EXPORTER_OTLP_CLIENT_KEY}"
        ${{ inputs.client_key }}
        EOF
        echo OTEL_EXPORTER_OTLP_CLIENT_KEY=${OTEL_EXPORTER_OTLP_CLIENT_KEY} >> ${GITHUB_ENV}