
name: 'Set OTEL_SERVICE_NAME from github job info'
description: |
    Obtains GitHub Actions job list and matches current job using runner name and attempt number.
    Returns name of current workflow, which will include any matrix components
    Sets the OTEL_SERVICE_NAME environment variable. Output is also here if you prefer.
outputs:
  name:
    description: 'The name of the job matching the current runner name and attempt number'
    value: ${{ steps.get-job-name.outputs.JOB_NAME }}

runs:
  using: 'composite'
  steps:
    # this checkout is goofy, but it's because we want to use the relative path to another reusable action.
    # From an external repo, that relative path won't be valid unless we do a source checkout of the shared-actions
    # repo. Pay attention to which repo you're pushing to. It's easy to wonder why you're not picking up changes.
    # It is likely that you are not pushing to the repo that is being cloned here.
    - uses: actions/checkout@v4
      with:
        repository: rapidsai/shared-actions
        path: ./shared-actions
    - uses: ./shared-actions/github-actions-job-info
      id: github-job-info
    - shell: bash
      id: get-job-name
      run:
        echo JOB_NAME="$(cat job_info.json | jq -r '.name')" >> ${GITHUB_OUTPUT};
    - shell: bash
      id: maybe-set-otel-service-name
      run: |
        if [ "$OTEL_SERVICE_NAME" = "" ]; then
          echo OTEL_SERVICE_NAME="${{steps.get-job-name.outputs.JOB_NAME}}" >> ${GITHUB_ENV};
        fi