name: dispatch-stash-base-env-vars
description: |
  Stores base environment variables in a file and uploads that file
  as an artifact. This action should only be called once in a build,
  at the start of the top-level workflow.

runs:
  using: 'composite'
  steps:
    # We can't use the load-then-clone action because the env vars file
    # that it needs is something that we create here.
    - name: Clone shared-actions repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO}}
        ref: ${{ env.SHARED_ACTIONS_REF}}
        path: ./shared-actions
    - name: Stash base env vars
      uses: ./shared-actions/telemetry-impls/stash-base-env-vars
