name: dispatch-setup
description: |
  This script sets important environment variables that may be used by tools that
  implement OpenTelemetry. This script also stores attributes (metadata) for the
  current job, so that this metadata can be associated with spans during the final
  parsing of job metadata.

  This is a wrapper that clones a specific branch/ref of the shared-actions repo, then
  executes the script in that branch/ref.


inputs:
  load_service_name:
    description: |
      If true, loads OTEL_SERVICE_NAME from the stashed env vars. This is used for top-level workflows.
      Otherwise the telemetry service name is obtained from Github job metadata.
      Getting the service name from Github job metadata is for child workflows.
    default: 'false'
  extra_attributes:
    description: "comma-separated key=value attributes to associate with the current job"

runs:
  using: 'composite'
  steps:
    - uses: rapidsai/shared-actions/telemetry-impls/load-then-clone@empty-certs
    - name: Set OTEL_SERVICE_NAME from job if not loading from stash
      if: ${{ inputs.load_service_name != 'true' }}
      uses: ./shared-actions/telemetry-impls/set-otel-service-name

    - name: Store attributes to use as metadata when creating spans
      # This also sets OTEL_RESOURCE_ATTRIBUTES, for any subsequent steps
      # in the calling workflow that might use it.
      uses: ./shared-actions/telemetry-impls/stash-job-attributes
      with:
        extra_attributes: ${{ inputs.extra_attributes }}
