name: 'Telemetry traceparent'
description: 'Outputs a trace identifier computed from the GitHub runtime environment. Requires the gha-tools repo to be on PATH.'
inputs:
  step_name:
    description: 'If this trace is for a step, provide the step name in addition to the job name'
outputs:
  traceparent:
    description: 'The OpenTelemetry span id of the span that should be used for the root span created here'
    value: ${{ steps.shell.outputs.TRACEPARENT }}

runs:
  using: 'composite'
  steps:
    - uses: ./shared-actions/telemetry-ensure-otel-cli-available
    # this ensures that OTEL_SERVICE_NAME is either set before this action, or sets it from the github job metadata
    - uses: ./shared-actions/set-otel-service-name-from-github
    - uses: ./shared-actions/telemetry-sanity-checks

    - shell: bash
      id: output-inputs
      if:  runner.debug == '1'
      run: |
        echo "::debug::trace ID input: '${GITHUB_REPOSITORY}+${GITHUB_RUN_ID}+${GITHUB_RUN_ATTEMPT}'"
        echo "::debug::$GITHUB_REPOSITORY="${GITHUB_REPOSITORY}""
        echo "::debug::$GITHUB_RUN_ID="${GITHUB_RUN_ID}""
        echo "::debug::$GITHUB_RUN_ATTEMPT="${GITHUB_RUN_ATTEMPT}""
        echo "::debug::Evaluated trace ID input (pre-hash): "${GITHUB_REPOSITORY}+${GITHUB_RUN_ID}+${GITHUB_RUN_ATTEMPT}""
        export TRACE_ID="$(rapids-get-telemetry-trace-id)"
        echo "::debug::Computed trace ID: ${TRACE_ID}"

        echo "::debug::JOB TRACEPARENT input (step empty): '00-\${TRACE_ID}-hash(\${TRACE_ID}-\$\{\OTEL_SERVICE_NAME}\})-01'"
        echo "::debug::evaluated job traceparent input: "00-${TRACE_ID}-hash\(${TRACE_ID}-${OTEL_SERVICE_NAME}\)-01""

        echo "::debug::JOB_SPAN_ID: '\${TRACE_ID}-\$\{OTEL_SERVICE_NAME\}'"
        echo "::debug::STEP TRACEPARENT input: '\${JOB_SPAN_ID}-\${STEP_NAME}'"
        echo "::debug::evaluated span traceparent input: "00-${TRACE_ID}-hash\(${TRACE_ID}-${OTEL_SERVICE_NAME}-${{inputs.step_name}}\)-01""

    - shell: bash
      id: shell
      run: |
        echo "TRACEPARENT=$(rapids-get-telemetry-traceparent "${OTEL_SERVICE_NAME}" "${{inputs.step_name}}")" >> ${GITHUB_OUTPUT}
