name: 'Telemetry traceparent'
description: 'Outputs a trace identifier computed from the GitHub runtime environment. Requires the gha-tools repo to be on PATH.'
inputs:
  step_name:
    description: 'If this trace is for a step, provide the step name in addition to the job name'
outputs:
  traceparent:
    description: 'The OpenTelemetry span id of the span that should be used for the root span created here'
    value: ${{ steps.shell.outputs.TRACEPARENT }}

runs:
  using: 'composite'
  steps:
    # TODO: This should be removed once otel-cli or its replacement is available in our ci images
    - shell: bash
      id: install-otel-cli
      run:
        if ! otel-cli --help  2>&1 >/dev/null; then
          ARCH=$(uname -m);
          if [ "$(uname -m)" = "x86_64" ]; then
            ARCH="amd64";
          else
            ARCH="arm64";
          fi;
          curl -L -o otel-cli-${ARCH}.tar.gz https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_0.4.5_linux_${ARCH}.tar.gz;
          tar -zxf  otel-cli-${ARCH}.tar.gz;
          mv otel-cli /usr/local/bin/;
        fi
    # Temporary until ci-imgs build with
    # https://github.com/rapidsai/gha-tools/commit/8bd8fca71b5fae38b1493c547d15e73da40b32e1#diff-f1f054b2906bfd36ad706ed2fa6aa028fa529e65b25167e4ca7ca45546d59ed8R14
    # is available. The PR is merged, but at time of writing, no ci-imgs builds have been released to pick it up.
    - name: Download gha-tools with git clone
      shell: bash
      run: |
          if [[ $(type rapids-get-telemetry-traceparent >/dev/null 2>&1) -eq 0 ]]; then
            git clone https://github.com/msarahan/gha-tools.git -b add-telemetry-traceparent-scripts /tmp/gha-tools;
            echo "/tmp/gha-tools/tools" >> "${GITHUB_PATH}";
          fi

    - uses: actions/checkout@v4
      with:
        repository: rapidsai/shared-actions
        ref: add-telemetry
        path: ./shared-actions
    - uses: ./shared-actions/set-otel-service-name-from-github
      id: get-job-name
    - shell: bash
      id: output-inputs
      run: |
        echo "trace ID input: '${GITHUB_REPOSITORY}+${GITHUB_RUN_ID}+${GITHUB_RUN_ATTEMPT}'"
        echo "$GITHUB_REPOSITORY="${GITHUB_REPOSITORY}""
        echo "$GITHUB_RUN_ID="${GITHUB_RUN_ID}""
        echo "$GITHUB_RUN_ATTEMPT="${GITHUB_RUN_ATTEMPT}""
        echo "Evaluated trace ID input (pre-hash): "${GITHUB_REPOSITORY}+${GITHUB_RUN_ID}+${GITHUB_RUN_ATTEMPT}""
        export TRACE_ID="$(rapids-get-telemetry-trace-id)"
        echo "Computed trace ID: ${TRACE_ID}"

        echo "JOB TRACEPARENT input (step empty): '00-\${TRACE_ID}-hash(\${TRACE_ID}-\$\{\OTEL_SERVICE_NAME}\})-01'"
        echo "evaluated job traceparent input: "00-${TRACE_ID}-hash\(${TRACE_ID}-${OTEL_SERVICE_NAME}\)-01""

        echo "JOB_SPAN_ID: '\${TRACE_ID}-\$\{\{steps.get-job-name.outputs.name\}\}'"
        echo "STEP TRACEPARENT input: '\${JOB_SPAN_ID}-\${STEP_NAME}'"
        echo "evaluated span traceparent input: "00-${TRACE_ID}-hash\(${TRACE_ID}-${OTEL_SERVICE_NAME}-${{inputs.step_name}}\)-01""

    - shell: bash
      id: shell
      run: |
        echo "TRACEPARENT=$(rapids-get-telemetry-traceparent "${OTEL_SERVICE_NAME}" "${{inputs.step_name}}")" >> ${GITHUB_OUTPUT}
