name: dispatch-stash-attributes
description: |
  Clones a particular branch/ref of a shared-actions repo, then
  call the stash-attributes implementation script, which writes
  some environment variables so that downstream jobs can refer to them.

  Inputs here are all assumed to be env vars set outside of this script.
  Set them in your main repo's workflows.
inputs:
  extra_attributes:
    description: "comma-separated key=value attributes to associate with the current job"


runs:
  using: 'composite'
  steps:
    - name: Clone shared-actions repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO || 'rapidsai/shared-actions' }}
        ref: ${{ env.SHARED_ACTIONS_REF || 'main' }}
        path: ./shared-actions
    - name: Stash current job's OTEL_RESOURCE_ATTRIBUTES
      uses: ./shared-actions/telemetry-impls/stash-job-attributes
      with:
        extra_attributes: ${{ inputs.extra_attributes }}
