name: 'Telemetry summarize'
description: |
  Consumes job info, parses into spans, and pushes spans.
inputs:
  cert_concat:
    description: Concatenation of certs (CA;Client;ClientKey)

runs:
  using: 'composite'
  steps:
    - uses: ./shared-actions/telemetry-impls/ensure-otel-cli-available
    # Writes JSON file that jobs below consume
    - uses: ./shared-actions/telemetry-impls/github-actions-job-info
      id: github-job-info
      with:
        all_jobs: true
    - uses: ./shared-actions/telemetry-impls/sanity-checks
    # This downloads ALL of the files that we have collected from each job.
    - uses: actions/download-artifact@v4
      with:
        path: attributes_files

    - shell: bash
      run: |
        set -e

        TOP_LEVEL_TRACEPARENT=${TRACEPARENT}

        for job_row in $(jq -r '.jobs[] | @base64' all_jobs.json); do

          job_name="$(echo ${job_row} | base64 --decode | jq -r ".name")"
          job_traceparent="$(rapids-get-telemetry-traceparent "${job_name}")"

          job_id="$(echo ${job_row} | base64 --decode | jq -r ".id")"
          attribute_file=./attributes_files/attrs-${job_id}

          # The reporting of the completion time is earlier than the actual last step's completion.
          # We compensate for that by picking up the last known completion time of any step.
          last_timestamp=$(date +'%s')

          # Base64 encoding is to avoid issues with spaces/newlines/whatever funny business
          for step_row in $(echo "${job_row}" | base64 --decode | jq -r '.steps[] | @base64'); do
              step_name="$(echo ${step_row} | base64 --decode | jq -r ".name")"
              conclusion="$(echo ${step_row} | base64 --decode | jq -r ".conclusion")"

              step_traceparent="$(rapids-get-telemetry-traceparent "${job_name}" "$step_name")";

              timestamp_as_date=$last_timestamp
              case $timestamp_as_date in
                  ''|*[!0-9]*) echo "Date is not an integer" ;;
                  *) timestamp_as_date="$(date -d @${last_timestamp} --rfc-3339=ns | sed "s/ /T/g" | sed "s/+00:00/Z/g")" ;;
              esac

              otel span create "$step_name" \
                  --attribute-file=${attribute_file}
                  --traceparent=${job_traceparent}
                  --trace-id="$(cut -d'-' -f2 <<<"$job_traceparent")" \
                  --span-id="$(cut -d'-' -f3 <<<"$step_traceparent")" \
                  --start="$(echo ${step_row} | base64 --decode | jq -r ".started_at // \"${timestamp_as_date}\"")" \
                  --end="$(echo ${step_row} | base64 --decode | jq -r ".completed_at // \"${timestamp_as_date}\"")" \

              # Compare timestamps; keep the latest one
              step_end_timestamp="$(echo ${step_row} | base64 --decode | jq -r ".completed_at")";
              if [ "$step_end_timestamp" != "null" ]; then
                step_end_timestamp=$(date -d "$step_end_timestamp" +'%s');
                if [ ${step_end_timestamp} -ge ${last_timestamp} ]; then
                  last_timestamp=${step_end_timestamp};
                fi
              fi
          done

          echo "Final timestamp is ${last_timestamp}"
          case $last_timestamp in
              ''|*[!0-9]*) echo "Date is not an integer" ;;
              *) last_timestamp="$(date -d @${last_timestamp} --rfc-3339=ns | sed "s/ /T/g" | sed "s/+00:00/Z/g")" ;;
          esac

          if [ "$status_description" != "" ] && [ "$status_description" != "null" ]; then
            status_description="--status-description ${status_description}"
          else
            status_description=
          fi

          # unset this so that the parent does not automatically get picked up
          if [ "${TOP_LEVEL_TRACEPARENT}" = "${job_traceparent}" ]; then
            otel span "workflow root" \
                  --attribute-file=${attribute_file}
                  --trace-id "$(cut -d'-' -f2 <<<"$job_traceparent")" \
                  --span-id "$(cut -d'-' -f3 <<<"$job_traceparent")" \
                  --start "${START_TIME}" \
                  --end "${last_timestamp}";
          else
            otel span "Start delay time" \
                  --attribute-file=${attribute_file}
                  --traceparent=${job_traceparent}
                  --trace-id "$(cut -d'-' -f2 <<<"$job_traceparent")" \
                  --span-id "$(cut -d'-' -f3 <<<"$job_traceparent")" \
                  --start "$(jq -r '.created_at // "now"' job_info.json)" \
                  --end "$(jq -r '.started_at // "now"' job_info.json)" \

            otel span "child workflow root" \
                  --attribute-file=${attribute_file}
                  --force-trace-id "$(cut -d'-' -f2 <<<"$job_traceparent")" \
                  --force-span-id "$(cut -d'-' -f3 <<<"$job_traceparent")" \
                  --traceparent ${TOP_LEVEL_TRACEPARENT} \
                  --start "$(jq -r '.created_at // "now"' job_info.json)" \
                  --end "${last_timestamp}";
          fi
        done
