name: 'Telemetry span creator'
description: 'Creates a span with the given traceparent and timestamp info'
inputs:
  default_endpoint:
    description: The server to send the span to
  service:
    description: The name of the service. This might be something like the root workflow file, or the repo, or PR number.
  name:
    description: The name of the span
  traceparent:
    description: 'The OpenTelemetry trace and span id of the span that will be created/updated'
    required: true
  start_time:
    description: 'start time of the span. Formatted as epoch: $(date +%s.%N)'
    required: true
  end_time:
    description: 'end time of the span. Optional. If not provided, defaults to "now".'
    default: "now"
  otel_resource_attributes:
    description: |
      Comma-separated key=value pairs used for storing additional "tags" to better identify data


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: rapidsai/shared-actions
        path: ./shared-actions
    - uses: ./shared-actions/github-actions-job-info
      id: github-job-info
    - shell: bash
      run: |
        export OTEL_EXPORTER_OTLP_ENDPOINT="${{inputs.default_endpoint}}"
        export OTEL_RESOURCE_ATTRIBUTES="${{inputs.otel_resource_attributes}}"
        end_time="${{inputs.end_time}}"
        if [ "${end_time}" = "now" ]; then
          end_time=$(date +%s.%N)
        fi
        trace_id="$(cut -d'-' -f2 <<<"${{inputs.traceparent}}")"
        span_id="$(cut -d'-' -f3 <<<"${{inputs.traceparent}}")"
        otel-cli span create \
          --service="${{inputs.service}}" \
          --name="${{inputs.name}}" \
          --start="${{inputs.start_time}}" \
          --end="${end_time}" \
          --force-trace-id="${trace_id}" \
          --force-span-id="${span_id}" \
          --verbose