name: 'Telemetry summarize'
description: 'Consumes job info, parses into spans, and pushes spans. Requires otel-cli and jq on PATH.'
inputs:
  traceparent:
    description: 'The OpenTelemetry span id of the span that new spans should be created under'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: rapidsai/shared-actions
        ref: add-telemetry
        path: ./shared-actions
    - uses: ./shared-actions/github-actions-job-info
      id: github-job-info
    - shell: bash
      run: |
        # This traceparent is the one that comes from outside; from any external job above this
        # Our job span should be a child of that trace. It is valid for this to be empty.
        export TRACEPARENT="${{inputs.traceparent}}"

        export OTEL_SERVICE_NAME="$(cat job_info.json | jq -r '.name' )"

        export job_traceparent="$(rapids-get-telemetry-traceparent "${OTEL_SERVICE_NAME}")"
        # TODO: Pass through attrs and friends. Maybe this is easier to do by just
        # setting the env var, though.

        status_description=$(cat job_info.json | jq '.conclusion')
        if [ "$status_description" != "" ] && [ "$status_description" != "null" ]; then
          status_description="--status-description ${status_description}"
        fi

        otel-cli span create \
                    --name "workflow root" \
                    --force-trace-id "$(cut -d'-' -f2 <<<"$job_traceparent")" \
                    --force-span-id "$(cut -d'-' -f3 <<<"$job_traceparent")" \
                    --start "$(cat job_info.json | jq -r '.created_at // "now"')" \
                    --end "$(cat job_info.json | jq -r '.completed_at // "now"')" \
                    --verbose \
                    $status_description

        # Nest the steps under the job we just made a span for. This sets the parent span ID for us.
        export TRACEPARENT=${job_traceparent}

        otel-cli span create \
                    --name "Start delay time" \
                    --start "$(cat job_info.json | jq -r '.created_at // "now"')" \
                    --end "$(cat job_info.json  | jq -r '.started_at // "now"')" \
                    --verbose

        # Each line is a step
        cat job_info.json | jq -c '.steps[]' | while read f; do
            name="$(echo "$f" | jq -r .name)";
            conclusion="$(echo "$f" | jq .conclusion)";

            step_traceparent="$(rapids-get-telemetry-traceparent "${OTEL_SERVICE_NAME}" "$name")"
            echo "OTEL_SERVICE_NAME: "${OTEL_SERVICE_NAME}", step_name: "$name"" >&2;
            echo "$step_traceparent" >&2;

            otel-cli span create \
                --name="$name" \
                --force-span-id="$(cut -d'-' -f3 <<<"$step_traceparent")" \
                --start="$(echo "$f" | jq -r '.started_at // "now"')" \
                --end="$(echo "$f" | jq -r '.completed_at // "now"')" \
                --verbose
        done
