name: 'Telemetry summarize'
description: 'Consumes job info, parses into spans, and pushes spans. Requires otel-cli and jq on PATH.'
inputs:
  traceparent:
    description: 'The OpenTelemetry span id of the span that new spans should be created under'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: rapidsai/shared-actions
        ref: add-telemetry
        path: ./shared-actions
    - uses: ./shared-actions/github-actions-job-info
      id: github-job-info
    - shell: bash
      run: |
        set -x
        # This traceparent is the one that comes from outside; from any external job above this
        # Our job span should be a child of that trace. It is valid for this to be empty.
        export TRACEPARENT="${{inputs.traceparent}}"

        export OTEL_SERVICE_NAME="$(cat job_info.json | jq -r '.name' )"
        export job_traceparent="$(rapids-get-telemetry-traceparent "${OTEL_SERVICE_NAME}")"

        # Nest the steps under the job we just made a span for. This sets the parent span ID for us.
        export TRACEPARENT=${job_traceparent}

        # The reporting of the completion time is earlier than the actual last step's completion.
        # We compensate for that by picking up the last known completion time of any step.
        last_timestamp=$(date +'%s.%N')

        # Base64 encoding is to avoid issues with spaces/newlines/whatever funny business
        for row in $(cat job_info.json | jq -r '.steps[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r "${1}"
            }

            name="$(_jq .name)";
            conclusion="$(_jq .conclusion)";

            step_traceparent="$(rapids-get-telemetry-traceparent "${OTEL_SERVICE_NAME}" "$name")";
            echo "OTEL_SERVICE_NAME: "${OTEL_SERVICE_NAME}", step_name: "$name"" >&2;
            echo "$step_traceparent" >&2;

            otel-cli span create \
                --name="$name" \
                --force-trace-id="$(cut -d'-' -f2 <<<"$job_traceparent")" \
                --force-span-id="$(cut -d'-' -f3 <<<"$step_traceparent")" \
                --start="$(_jq ".started_at // ${last_timestamp}")" \
                --end="$(_jq ".completed_at // ${last_timestamp}")" \
                --verbose

            # Compare timestamps; keep the latest one
            step_end_timestamp="$(_jq '.completed_at')";
            if [ "$step_end_timestamp" != "null" ]; then
              step_end_timestamp=$(date -d "$step_end_timestamp" +'%s.%N');
              if [ ${step_end_timestamp} -ge ${last_timestamp} ]; then
                last_timestamp=${step_end_timestamp};
                echo "Set timestamp to ${last_timestamp}";
              fi
            fi
        done

        echo "Final timestamp is ${last_timestamp}"

        if [ "$status_description" != "" ] && [ "$status_description" != "null" ]; then
          status_description="--status-description ${status_description}"
        else
          status_description=
        fi

        # This is (unintuitively) set here because we don't know the true end time until we
        # go though the steps.
        otel-cli span create \
                    --name "workflow root" \
                    --force-trace-id "$(cut -d'-' -f2 <<<"$job_traceparent")" \
                    --force-span-id "$(cut -d'-' -f3 <<<"$job_traceparent")" \
                    --start "$(_jq ".created_at // ${last_timestamp}")" \
                    --end ${last_timestamp} \
                    --verbose \
                    $status_description

        otel-cli span create \
                    --name "Start delay time" \
                    --force-trace-id "$(cut -d'-' -f2 <<<"$job_traceparent")" \
                    --start "$(cat job_info.json | jq -r '.created_at // "now"')" \
                    --end "$(cat job_info.json  | jq -r '.started_at // "now"')" \
                    --verbose
