on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  compute_traceparent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      # Temporary until ci-imgs build with
      # https://github.com/rapidsai/gha-tools/commit/8bd8fca71b5fae38b1493c547d15e73da40b32e1#diff-f1f054b2906bfd36ad706ed2fa6aa028fa529e65b25167e4ca7ca45546d59ed8R14
      # is available. The PR is merged, but at time of writing, no ci-imgs builds have been released to pick it up.
      - name: Download gha-tools with git clone
        shell: bash
        run: |
            if [[ ! -d /tmp/gha-tools ]]; then
                git clone https://github.com/msarahan/gha-tools.git -b add-telemetry-traceparent-scripts /tmp/gha-tools;
                echo "/tmp/gha-tools/tools" >> "${GITHUB_PATH}";
            fi
      - name: test traceparent script at top level
        run: |
            echo $(rapids-get-telemetry-traceparent)
      - name: Get job traceparent
        uses: ./telemetry-traceparent
        id: job-traceparent
      - name: Echo value from job
        run: echo "${{steps.job-traceparent.outputs.traceparent}}"
  example_matrix:
    name: Test ${{ matrix.os}}-${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2]
        os: [ubuntu-latest] # , windows-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      # Temporary until ci-imgs build with
      # https://github.com/rapidsai/gha-tools/commit/8bd8fca71b5fae38b1493c547d15e73da40b32e1#diff-f1f054b2906bfd36ad706ed2fa6aa028fa529e65b25167e4ca7ca45546d59ed8R14
      # is available. The PR is merged, but at time of writing, no ci-imgs builds have been released to pick it up.
      - name: Download gha-tools with git clone
        shell: bash
        run: |
            if [[ ! -d /tmp/gha-tools ]]; then
                git clone https://github.com/msarahan/gha-tools.git -b add-telemetry-traceparent-scripts /tmp/gha-tools;
                echo "/tmp/gha-tools/tools" >> "${GITHUB_PATH}";
            fi

      # Run job with traceparent. We'll validate that this matches in the summary data.
      - name: Get job traceparent in matrix job
        uses: ./telemetry-traceparent
        id: job-traceparent
      - name: Generate traceparent for a step
        uses: ./telemetry-traceparent
        id: step-traceparent
        with:
            step_name: "Download gha-tools with git clone"
      - name: Echo computed step traceparent
        run: |
            echo "GHA tools clone job traceparent: ${{ steps.step-traceparent.outputs.traceparent }}"
      - name: Test OTel export of job JSON
        uses: ./telemetry-summarize
        with:
            traceparent: ${{ steps.job-traceparent.outputs.traceparent}}
