name: 'Telemetry sanity checks'
description: 'Ensures that necessary components and env vars are available'
runs:
  using: 'composite'
  steps:
    - shell: bash
      id: checks
      run: |
        echo "OTEL_SERVICE_NAME is ${OTEL_SERVICE_NAME}"
        if [ "${OTEL_SERVICE_NAME}" = "" ]; then
          echo "OTEL_SERVICE_NAME is empty. Erroring out.";
          exit 1;
        fi
